[build]
  command = "npm install --legacy-peer-deps && CI= npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_PREFLIGHT_CHECK = "true"
